CREATE TABLE IF NOT EXISTS vecinos (
  piso VARCHAR(255) NOT NULL,
  serial_number VARCHAR(255),
  device_identification VARCHAR(255),
  nombre VARCHAR(255),
  email VARCHAR(255),
  coeficiente VARCHAR(255),
  password_hash TEXT,
  enviar_email BOOLEAN NOT NULL DEFAULT false,
  CONSTRAINT vecinos_pkey PRIMARY KEY (piso)
);

CREATE TABLE IF NOT EXISTS contadores (
  serial_number BIGINT NOT NULL,
  primary_address BIGINT,
  device_identification VARCHAR(255) NOT NULL,
  value_data_count BIGINT,
  manufacturer VARCHAR(255),
  version BIGINT,
  device_type VARCHAR(255),
  access_number BIGINT,
  status BIGINT,
  signature BIGINT,
  energy_wh_inst_value_0_0_0 BIGINT,
  energy_manufacturer_specific_02_wh_inst_value_0_0_0 BIGINT,
  manufacturer_specific_ff_07_inst_value_0_0_0 BIGINT,
  manufacturer_specific_ff_08_inst_value_0_0_0 BIGINT,
  volume_m3_inst_value_0_0_0 REAL,
  volume_m3_inst_value_0_1_0 REAL,
  volume_m3_inst_value_0_2_0 REAL,
  on_time_hours_inst_value_0_0_0 BIGINT,
  on_time_hours_err_value_0_0_0 BIGINT,
  flow_temp_c_inst_value_0_0_0 REAL,
  return_temp_c_inst_value_0_0_0 REAL,
  diff_temp_k_inst_value_0_0_0 REAL,
  power_w_inst_value_0_0_0 BIGINT,
  volume_flow_m3h_inst_value_0_0_0 REAL,
  manufacturer_specific_ff_22_inst_value_0_0_0 BIGINT,
  datetime_inst_value_0_0_0 TIMESTAMP,
  energy_wh_inst_value_0_0_1 BIGINT,
  energy_manufacturer_specific_02_wh_inst_value_0_0_1 BIGINT,
  manufacturer_specific_ff_07_inst_value_0_0_1 BIGINT,
  manufacturer_specific_ff_08_inst_value_0_0_1 BIGINT,
  volume_m3_inst_value_0_0_1 REAL,
  volume_m3_inst_value_0_1_1 REAL,
  volume_m3_inst_value_0_2_1 REAL,
  power_w_max_value_0_0_1 BIGINT,
  volume_flow_m3h_max_value_0_0_1 REAL,
  date_inst_value_0_0_1 TIMESTAMPTZ,
  manufacturer_specific_ff_1a_inst_value_0_0_0 BIGINT,
  fabrication_no_inst_value_0_0_0 BIGINT,
  manufacturer_specific_ff_16_inst_value_0_0_0 BIGINT,
  manufacturer_specific_ff_17_inst_value_0_0_0 BIGINT,
  created TIMESTAMPTZ NOT NULL,
  device_position VARCHAR(255),
  CONSTRAINT contadores_pkey PRIMARY KEY (device_identification, serial_number, created)
);

CREATE TABLE IF NOT EXISTS facturas (
  id_factura VARCHAR(255) NOT NULL,
  piso VARCHAR(255),
  nombre VARCHAR(255),
  email VARCHAR(255),
  device_position_ini VARCHAR(255),
  device_position_fin VARCHAR(255),
  device_identification VARCHAR(255),
  fecha_factura_creacion TIMESTAMPTZ,
  fecha_factura_inicio TIMESTAMPTZ,
  fecha_factura_fin TIMESTAMPTZ,
  fecha_lectura_inicio TIMESTAMPTZ,
  fecha_lectura_fin TIMESTAMPTZ,
  importe_vivienda_total REAL,
  importe_vivienda_fijo REAL,
  importe_vivienda_variable_calor REAL,
  importe_vivienda_variable_frio REAL,
  importe_vivienda_variable_acs REAL,
  importe_vivienda_acs REAL,
  coeficiente_vivienda REAL,
  porcentaje_coeficiente_vivienda REAL,
  m3_vivienda_acs_inicial REAL,
  m3_vivienda_acs_final REAL,
  m3_vivienda_acs REAL,
  kwh_vivienda_acs BIGINT,
  importe_factura_electrica REAL,
  importe_total_fijo REAL,
  importe_total_variable REAL,
  importe_kwh REAL,
  importe_m3_acs REAL,
  kwh_vivienda_calor_inicial BIGINT,
  kwh_vivienda_calor_final BIGINT,
  kwh_vivienda_frio_inicial BIGINT,
  kwh_vivienda_frio_final BIGINT,
  kwh_vivienda_calor BIGINT,
  kwh_vivienda_frio BIGINT,
  kwh_total_viviendas BIGINT,
  enviar_email BOOLEAN NOT NULL DEFAULT false,
  id_factura_electrica VARCHAR(255),
  fecha_h_factura_creacion VARCHAR(255),
  fecha_h_factura_inicio VARCHAR(255),
  fecha_h_factura_fin VARCHAR(255),
  fecha_h_lectura_inicio VARCHAR(255),
  fecha_h_lectura_fin VARCHAR(255),
  kwh_m3_calentar_acs REAL,
  CONSTRAINT facturas_pkey PRIMARY KEY (id_factura)
);
